### ISSUE TITLE
项目完善程度

### ISSUE THREAD

**Issue by zhurou603** [wzhe06/SparrowRecSys#2]
请问老师现在是一个完整项目了吗?感觉似乎很多模块不知道去哪里访问?比如召回排序等

**Comment by wzhe06** [comment]
目前还不是，如果你是极客时间课程的用户的话，会随着课程的进行逐渐完善。后续包括model serving，排序，tensorflow模型训练等模块都会逐渐加入。

**Comment by bytemani** [comment]
现在完善了不？
