### ISSUE TITLE
Unimplemented: Cast string to int32 is not supported

### ISSUE THREAD

**Issue by hzjiang1994** [wzhe06/SparrowRecSys#26]
when run WideNDeep.py,the bugs happens

**Comment by hzjiang1994** [comment]
![image](https://user-images.githubusercontent.com/54624640/104400786-ef642700-558d-11eb-87d6-61927d95bc45.png)

**Comment by jackyideal123** [comment]
i got the same issue. what should we do?

**Comment by jackyideal123** [comment]
Cast string to int32 is not supported question

**Comment by jiahenghuang** [comment]
一样的问题，换了2.0.0的版本就好了。
看大家都是中国人，我就用中文了。

**Comment by mokundong** [comment]
> 一样的问题，换了2.0.0的版本就好了。
> 看大家都是中国人，我就用中文了。

2.0.0和2.2.0都还是这样

**Comment by CaiJonhK** [comment]
报错时tf版本2.2.0，升级成2.3.0解决
