### ISSUE TITLE
Format with google-java-format

### ISSUE THREAD

**Issue by YikSanChan** [wzhe06/SparrowRecSys#7]
The code format is a little bit off. Will you consider formatting the code base with https://github.com/google/google-java-format, and furthermore make it part of the build process? This way no code without being properly formatted can be checked in.

**Comment by wzhe06** [comment]
This is a good point for sure. While SparrowRecSys in this stage is mainly for beginners' practicing and more modules and languages may be added to this project meanwhile. Let's do stricter format check after all main modules has been added. And I will transfer the project to a formal open source project by then.  Thx.

**Comment by YikSanChan** [comment]
Sounds good

Wang Zhe <notifications@github.com>于2020年10月5日 周一上午12:12写道：
